

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/database/public/css/Table.css">
</head>

<body>
 
    <br><br><br>
<h2>Table using this form</h2>

<div class="tab">
  <button class="tablinks" onclick="openCity(event, 'table1')">Art Object</button>
  <button class="tablinks" onclick="openCity(event, 'table2')">Artist</button>
  <button class="tablinks" onclick="openCity(event, 'table3')">Exhibition</button>
  <button class="tablinks" onclick="openCity(event, 'table4')">Collection</button>
   <?php
   if(session_status() == 1){
    session_start();}
    $temp = $_SESSION['role_id'];
    $rol  = Permission::findFirst([
        'role_id = ?0 AND permission_id = ?1',
        'bind' => [
            0 => $temp,
            1 => 4,
        ]
    ]);
    if ($rol !== false) {
   ?>
  <button class="tablinks" onclick="openCity(event, 'table5')">Edit User(Manager Only)</button>
  <?php 
  }
  ?>
</div>

<div id="table1" class="tabcontent" style="display: none;">
    <button class="button button1" onclick="window.location.href='/database/art/choose'">ADD</button>
    <table id="t01">
      <tr>
        <th>Id_no</th>
        <th>Year</th> 
        <th>Name</th>
        <th>Detail</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <tr>
        <?php 
            $count = ArtObjects::find();
            $num = count($count);
            for($i=1;$i<=$num;$i++)
           {
            $art = ArtObjects::findFirst([
                        'id_no = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
            if ($art === false) {$num++;continue;}
                
        ?>
        <td><?php echo $art->id_no ; ?></td>
        <td><?php echo $art->year ; ?></td> 
        <td><?php echo $art->title ; ?></td>
        <td><button class="button button1" onclick="window.location.href='/database/art/detail/<?php echo $i;?>'">More</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/art/edit/<?php echo $i;?>'">Edit</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/art/delete/<?php echo $i;?>'">Delete</button></td>
      </tr>
      <?php }?>
    </table>
</div>

<div id="table2" class="tabcontent" style="display: none;">
<button class="button button1" onclick="window.location.href='/database/artist/add'">ADD</button>
<table id="t01">
      <tr>
        <th>Id_no</th>
        <th>Name</th> 
        <th>Detail</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <tr>
        <?php 
            $count = Artist::find();
            $num = count($count);
            for($i=1;$i<=$num;$i++)
           {
            $art = Artist::findFirst([
                        'artist_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
            if ($art === false) {$num++;continue;}
        ?>
        <td><?php echo $art->artist_id ; ?></td>
        <td><?php echo $art->firstname." ".$art->midname." " .$art->lastname ; ?></td>
        <td><button class="button button1" onclick="window.location.href='/database/artist/detail/<?php echo $i;?>'">More</button></td>
        <td><button class="button button2" onclick="window.location.href='/database/artist/edit/<?php echo $i;?>'">Edit</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/artist/delete/<?php echo $i;?>'">Delete</button></td>
      </tr>
      <?php }?>
    </table>
</div>

<div id="table3" class="tabcontent" style="display: none;">
<button class="button button1" onclick="window.location.href='/database/exhibitions/add'">ADD</button>
<table id="t01">
      <tr>
        <th>Ex_Id</th>
        <th>Name</th> 
        <th>Detail</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>AddGoer</th>
        <th>DelGoer</th>
      </tr>
      <tr>
        <?php 
            $count = Exhibitions::find();
            $num = count($count);
            for($i=1;$i<=$num;$i++)
           {
            $art = Exhibitions::findFirst([
                        'ex_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
            if ($art === false) {$num++;continue;}
        ?>
        <td><?php echo $art->ex_id ; ?></td>
        <td><?php echo $art->ex_name; ?></td>
        <td><button class="button button1" onclick="window.location.href='/database/exhibitions/detailexhibition/<?php echo $i;?>'">More</button></td>
        <td><button class="button button2" onclick="window.location.href='/database/exhibitions/edit/<?php echo $i;?>'">Edit</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/exhibitions/delete/<?php echo $i;?>'">Delete</button></td>
        <td><button class="button button2" onclick="window.location.href='/database/exhibitions/addGo/<?php echo $i;?>'">Add</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/exhibitions/deleteGo/<?php echo $i;?>'">Delete</button></td>
      </tr>
      <?php }?>
    </table>
</div>

<div id="table4" class="tabcontent" style="display: none;">
<button class="button button1" onclick="window.location.href='/database/collection/add'">ADD</button>
<table id="t01">
      <tr>
        <th>Collection_Id</th>
        <th>Name</th> 
        <th>Detail</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <tr>
        <?php 
            $count = Collections::find();
            $num = count($count);
            for($i=1;$i<=$num;$i++)
           {
            $art = Collections::findFirst([
                        'Collections_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
            if ($art === false) {$num++;continue;}
        ?>
        <td><?php echo $art->Collections_id ; ?></td>
        <td><?php echo $art->name; ?></td>
        <td><button class="button button1" onclick="window.location.href='/database/collection/detail/<?php echo $i;?>'">More</button></td>
        <td><button class="button button2" onclick="window.location.href='/database/collection/edit/<?php echo $i;?>'">Edit</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/collection/delete/<?php echo $i;?>'">Delete</button></td>
      </tr>
      <?php }?>
    </table>
</div>

<div id="table5" class="tabcontent" style="display: none;">
<table id="t01">
      <tr>
        <th>User_Id</th>
        <th>Username</th> 
        <th>Role</th>
        <th>Status</th>  
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <tr>
        <?php 
            $count = User::find();
            $num = count($count);
            for($i=1;$i<=$num;$i++)
           {
            $art = User::findFirst([
                        'user_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
            if ($art === false) {$num++;continue;}
            $rol = Role::findFirst([
                'idrole = ?0',
                'bind' => [
                    0 => $art->role_id,
                ]
            ]);
        ?>
        <td><?php echo $art->user_id ; ?></td>
        <td><?php echo $art->username; ?></td>
        <td><?php echo $rol->rolename; ?></td>
        <td><?php echo $art->status; ?></td>
        <td><button class="button button2" onclick="window.location.href='/database/user/edit/<?php echo $i;?>'">Edit</button></td>
        <td><button class="button button1" onclick="window.location.href='/database/user/delete/<?php echo $i;?>'">Delete</button></td>
      </tr>
      <?php }?>
    </table>
</div>

<script>
function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>

</body>
</html>
