<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Bootstrap tutorials by Siam HTML</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

</head>


<body>
  <img src="img\glyphicons-halflings.png" class="img-fluid mx-auto d-block" alt="Responsive image" width="900">
  <p class="font-weight-bold">
    <font size="36">
      <center>Sculpture</center>
    </font>
  </p>

  <center>
    <div class="container">
      <div class="row">
        <div class="card-deck">
          <div class="card mb-3">
            <img class="card-img-mid" src="img/David.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="card-deck">
          <div class="card mb-3">
            <img class="card-img-mid" src="img/David.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
          <div class="card mb-3">
            <img class="card-img-mid" src="img/Feast of the rosary.jpg" alt="Card image cap" style="max-height: 18rem">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
            </div>
          </div>
        </div>
      </div>
  </center>





</body>