<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Bootstrap tutorials by Siam HTML</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

</head>

<body>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 ">                
                <div class="card border-dark mb-3" style="width: 370px; height: 500px;">
                    <img class="card-img-top" src="img\glyphicons-halflings.png" alt="Card image cap" style="width: 365px; height: 500px;">
                    <div class="card-body">
                      <h5 class="card-title-italic"><center>NAME</center></h5>
                    </div>
                  </div>
            </div>                

            <div class="col-8">
                <div class="row">
                    <div class="col-8">
                        <div class="row">
                            <div class="col-6"></div>
                            <div class="col-6">
                                <div class="card border-dark mb-3" style="max-width: 20rem;">
                                    <div class="card-header "><center>MAIN_STYLE</div>
                                    <div class="card-body text-dark">
                                        <p class="card-text">Some</p>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-3">
                        <div class="card border-dark mb-1" style="max-width: 20rem;">
                            <div class="card-header "><center>DATE_BORN</center></div>
                            <div class="card-body text-dark">
                                <p class="card-text">Some</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="card border-dark mb-1" style="max-width: 20rem;">
                            <div class="card-header "><center>DATE_DIE</center></div>
                            <div class="card-body text-dark">
                                <p class="card-text">Some</p>
                            </div>
                        </div>

                    </div>
                    <div class="col-4">
                        <div class="card border-dark mb-1" style="max-width: 20rem;">
                            <div class="card-header "><center>COUNTRY</center></div>
                            <div class="card-body text-dark">
                                <p class="card-text">Some</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="card border-dark mb-2" style="max-width: 20rem;">
                            <div class="card-header "><center>EPOCH</center></div>
                            <div class="card-body text-dark">
                                <p class="card-text">Some</p>
                            </div>
                        </div>

                    </div>
                </div>               
                <div class="row">
                    <div class="col-12">
                        <div class="card border-dark mb-1" style="height: 15rem;">
                            <div class="card-header "><center>Descripsion</center></div>
                            <div class="card-body text-dark">
                                <p class="card-text">Some</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

</body>

</html>