<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Home </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <!--<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto"></ul>
            <ul class="navbar-nav  navbar-right">     
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="login" class="btn "> Login </a>
                </li>    
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="index" class="btn "> Home </a>
                </li>
            </ul>
        </div>
    </div>
</nav>-->

</head>


<body>
    <img src="public\img\exhibitions\glyphicons-halflings.png" class="img-fluid mx-auto d-block" alt="Responsive image" width="1200">
    <p class="font-weight-bold">
        <font size="36">           
        </font>
    </p><br><br>
    <div class="container">       
        <div class="row">
            <div class="col-2">
                <div class="card mb-3">
                    <div class="card-body">
                    DATE
                    </div>
                  </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                      Exhibition name
                    </div>
                  </div>
            </div>
            <div class="col-2 ">
                <div class="card">
                    <div class="card-body">
                      gore
                    </div>
                  </div>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <div class="card mb-3">
                    <div class="card-body">
                    DATE
                    </div>
                  </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                      Exhibition name
                    </div>
                  </div>
            </div>
            <div class="col-2 ">
                <div class="card">
                    <div class="card-body">
                      gore
                    </div>
                  </div>
            </div>
        </div>
        <div class="row">
            <div class="col-2 mb-3">
                <div class="card">
                    <div class="card-body">
                    DATE
                    </div>
                  </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                      Exhibition name
                    </div>
                  </div>
            </div>
            <div class="col-2 ">
                <div class="card">
                    <div class="card-body">
                      gore
                    </div>
                  </div>
            </div>
        </div>
        <div class="row">
            <div class="col-2 mb-3">
                <div class="card">
                    <div class="card-body">
                    DATE
                    </div>
                  </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                      Exhibition name
                    </div>
                  </div>
            </div>
            <div class="col-2 ">
                <div class="card">
                    <div class="card-body">
                      gore
                    </div>
                  </div>
            </div>
        </div>

   
</div>
</center>


</body>
</html>
