<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Home </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <!--<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto"></ul>
            <ul class="navbar-nav  navbar-right">     
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="login" class="btn "> Login </a>
                </li>    
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="index" class="btn "> Home </a>
                </li>
            </ul>
        </div>
    </div>
</nav>-->

</head>

<?php
  $count = Exhibitions::find();
  $num = count($count);
  ?>

<body>
    <img src="public/img/Main/exhibition.jpg" class="img-fluid mx-auto d-block" alt="Responsive image" width="1200">
    <p class="font-weight-bold">
        <font size="36">           
        </font>
    </p><br><br>
    <div class="container">       
        <div class="row">
            <?php
            $i = 0;
            while($i<$num)
            {
            ?>
            <div class="col-2">
                <div class="card mb-3">
                    <div class="card-body">
                    <?php echo $count[$i]->start_date; ?> - <?php echo $count[$i]->end_date; ?> 
                    </div>
                  </div>
            </div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                    <?php echo $count[$i]->ex_name; ?>
                    </div>
                  </div>
            </div>
            <div class="col-2 ">
                <div class="card">
                    <div class="card-body">
                    <button class="button button1" onclick="window.location.href='/database/exhibitions/detailexhibition/<?php echo $count[$i]->ex_id;?>'">Click</button>
                    </div>
                  </div>
            </div>
            <?php $i++;} ?>
        </div>
</div>
</body>
</html>
