
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Home </title>
    <link rel="stylesheet" href="css/stylehome.css">
    <!-- <link rel="stylesheet" href="animate.css"> -->
    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">  -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> --> -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</head>
  
  <body>    
        <p>
        <img border="0" alt="W3Schools" src="public/img/Main/artmuseum.jpg" width="1280" height="960">
        </p>
        <br><br><br>
        <div class ="Painting" align = center>
          <img border="0" alt="W3Schools" src="public/img/Main/painting.jpg" width="1920" height="1280">
            <div class ="overlay">
              <div class ="content">
                <a href="paint" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>

        <div class ="Painting" align = center>
        <img border="0" alt="W3Schools" src="public/img/Main/sculptures.jpg" width="1920" height="1280">
            <div class ="overlay">
              <div class ="content">
                <a href="sculpture" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>
        
        <div class ="Painting" align = center>
        <img border="0" alt="W3Schools" src="public/img/Main/statues.jpg" width="6000" height="4000">
            <div class ="overlay">
              <div class ="content">
                <a href="Statue" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>
        
        <div class ="Painting" align = center>
        <img border="0" alt="W3Schools" src="public/img/Main/others.jpg" width="1280" height="960">
            <div class ="overlay">
              <div class ="content">
                <a href="other" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>
        
        <div class ="Painting" align = center>
        <img border="0" alt="W3Schools" src="public/img/Main/exhibition.jpg" width="1280" height="960">
            <div class ="overlay">
              <div class ="content">
                <a href="exhibitions" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>
        
        <div class ="Painting" align = center>
        <img border="0" alt="W3Schools" src="public/img/Main/meets.jpg" width="1280" height="960">
            <div class ="overlay">
              <div class ="content">
                <a href="meet" class btn >View more</a>
              </div>        
            </div>        
        </div>
        <br><br>
     

    <div class="w3-main w3-padding-large" style="margin-left:40%">

<!-- Menu icon to open sidebar -->

  <div class="w3-padding-32 w3-content w3-text-grey" id="contact" style="margin-bottom:64px">
  <h2>Contact Me</h2>
  <hr class="w3-opacity">

  <div class="w3-section">
    <p><i class="fa fa-map-marker fa-fw w3-xxlarge w3-margin-right"></i> Chicago, US</p>
    <p><i class="fa fa-phone fa-fw w3-xxlarge w3-margin-right"></i> Phone: +00 151515</p>
    <p><i class="fa fa-envelope fa-fw w3-xxlarge w3-margin-right"> </i> Email: mail@mail.com</p>
  </div>
  
    </div>    
 
  </body>
</html>























