
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Home </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <!--<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto"></ul>
            <ul class="navbar-nav  navbar-right">     
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="login" class="btn "> Login </a>
                </li>    
                <li class="nav-item mx-0 mx-lg-1">
                    <a href="index" class="btn "> Home </a>
                </li>
            </ul>
        </div>
    </div>
</nav>-->

</head>

  <body>
  
        <p>
        <img border="0" alt="W3Schools" src="public/img/Main/artmuseum.jpg" width="1280" height="960">
        </p>

        <p>        <a href="paint">
        <img border="0" alt="W3Schools" src="public/img/Main/paint.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="sculpture">
        <img border="0" alt="W3Schools" src="public/img/Main/sculpture.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="state">
        <img border="0" alt="W3Schools" src="public/img/Main/state.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="other">
        <img border="0" alt="W3Schools" src="public/img/Main/other.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="exhibitions">
        <img border="0" alt="W3Schools" src="public/img/Main/exhibitions.jpg" width="1280" height="960" href="/database/exhibition" class="btn " >
        </a>        </p>

        <p>        <a href="contract">
        <img border="0" alt="W3Schools" src="public/img/Main/contract.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="meet">
        <img border="0" alt="W3Schools" src="public/img/Main/meet.jpg" width="1280" height="960">
        </a>        </p>

        <p>        <a href="quate">
        <img border="0" alt="W3Schools" src="public/img/Main/quate.jpg" width="1280" height="960">
        </a>        </p>
 
  </body>
</html>























