<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="/database/public/css/Table.css">
    </head>

    <?php 
    if(session_status() == 1){
    session_start();}
    $role_id = $_SESSION['role_id'];
    $rol  = Permission::findFirst([
            'role_id = ?0 AND permission_id = ?1',
            'bind' => [
                0 => $role_id,
                1 => 3,
            ]
        ]);
        if ($rol === false) {
            ?>
          <script>
                    alert("You Haven't Permission to do this");
                    window.location = "../../table";
            </script>
            <?php
        }
    ?>
 
    <body id="page-top" >
 
    <br><br><br>
<h2>All in Table will be set to Null</h2>
<br>
<table id="t01">
      <tr>
        <th>ArtObject_id</th>
        <th>Name</th>
      </tr>
      <tr>
        <?php 
            $count = ArtObjects::find([
                'artist_id = ?0',
                'bind' => [
                    0 => $id,
                ]
            ]);
            for($i=0;$i<count($count);$i++)
           {         
        ?>
        <td><?php echo $count[$i]->id_no ; ?></td>
        <td><?php echo $count[$i]->title ; ?></td>
        
      </tr>
      <?php }?>
      
    </table>
    <button class="button button1" onclick="window.location.href='/database/table'">Back</button>
    <button class="button button1" onclick="window.location.href='/database/artist/confirm/<?php echo $id;?>'">Delete</button>
</body>
 

</html>

