<!DOCTYPE html>
<html lang="en">
 
<head>
    <link rel="stylesheet" href="/database/public/css/TableEdit.css">
</head>
 
<body>
    <br><br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 ">                
               <br> <img class="img-fluid" src="../../public/img/artist/<?php echo $image;?>" alt="Chania">
            </div>
               


            <div class="col-8 bg-light">
            <form action="../submit/<?php echo $artist_id;?>" method="post" enctype="multipart/form-data">
                <label for="name">Firstname</label><br>
                <input type="text" name="firstname" id="firstname" value="<?php echo $firstname;?>"><br>               
                <label for="name">Midname</label><br>
                <input type="text" name="midname" id="midname" value="<?php echo $midname;?>"><br>
                <label for="name">Lastname</label><br>
                <input type="text" name="lastname" id="lastname" value="<?php echo $lastname;?>"><br><br>     

                <label for="dateborn">Date_Born</label>
                <input type="date" name="date_born" id="date_born" value="<?php echo $date_born;?>">
                <label for="datedie">Date_Die</label>
                <input type="date" name="date_die" id="date_die" value="<?php echo $date_die;?>" ><br><br>
                
                <label for="country">Country</label><br>
                <select name="country" id="country">
                <?php 
                $count = Country::find();
                $num = count($count);
            
                for($i=1;$i<=$num;$i++)
                {
                    $art = Country::findFirst([
                        'country_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                    if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->country_id;?>" <?php if($country == $art->country_title){echo "selected";}?>><?php echo $art->country_id." - ".$art->country_title;?></option> 
                <?php
                }
                ?>                             
                </select>
                
                <label for="epoch">Epoch</label><br>
                <select name="epoch" id="epoch">
                <?php 
                $count2 = Epoch::find();
                $num = count($count2);
            
                for($i=1;$i<=$num;$i++)
                {
                    $art = Epoch::findFirst([
                        'epoch_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                    if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->epoch_id;?>" <?php if($epoch == $art->epoch_title){echo "selected";}?>><?php echo $art->epoch_id." - ".$art->epoch_title;?></option>   
                <?php
                }
                ?>                             
                </select>
                
                <label for="des">Description</label><br>
                <textarea name="des" id="des" rows="10" cols="100"><?php echo $des;?></textarea><br>

                <br>
                <h3>Select image to upload:</h3>
                <input type="file" name="fileToUpload" id="fileToUpload"> 

                <input type="submit" value="Submit">
                </form>
                <button class="button button1" onclick="window.location.href='/database/table'">Back</button>
            </div>
            

            </div>
        </div>
 
</body>
 
</html>