<!DOCTYPE html>
<html>
<head>
</head>
<body>
</body>

<?php 
    if(session_status() == 1){
    session_start();}
    $role_id = $_SESSION['role_id'];
    $rol  = Permission::findFirst([
            'role_id = ?0 AND permission_id = ?1',
            'bind' => [
                0 => $role_id,
                1 => 3,
            ]
        ]);
        if ($rol === false) {
            ?>
            <script>
                    alert("You Haven't Permission to do this");
                    window.location = "../../table";
            </script>
            <?php
        }else{
        $this->response->redirect('collection/deletesub/'.$id);
        }
?>