<!DOCTYPE html>
<html lang="en">
 
<head>
    <link rel="stylesheet" href="/database/public/css/TableEdit.css">
</head>
 
<body>
    <br><br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 ">                
               
            </div>
               
            <div class="col-8 bg-light">
            <form action="/database/collection/submit/<?php echo $id;?>" method="post" enctype="multipart/form-data">
                <label for="coname">Collection Name</label><br>
                <input type="text" name="coname" id="coname" value="<?php echo $coname;?>"><br>
                <label for="type">Type</label><br>
                <input type="text" name="type" id="type" value="<?php echo $type;?>"><br>
                <label for="des">Description</label><br>
                <input type="text" name="des" id="des" value="<?php echo $des;?>"><br>
                <label for="addr">Address</label><br>
                <input type="text" name="addr" id="addr" value="<?php echo $addr;?>"><br>
                <label for="phone">Phone</label><br>
                <input type="text" name="phone" id="phone" value="<?php echo $phone;?>"><br>
                <label for="cont">Contact</label><br>
                <input type="text" name="cont" id="cont" value="<?php echo $cont;?>"><br>
                <br>
                <input type="submit" value="Submit"><br>
                <br>

            </form>
                <button class="button button1" onclick="window.location.href='/database/table'">Back</button>
            </div>
            

            </div>
        </div>
 
</body>
 
</html>