<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="public/css/style.css">
    </head>
 
    <body id="page-top" >

</body>
<br><br>

    <br><br>
<h2>Welcome to Ours museum</h2>
<h1>LOG-IN</h1>
<br>
<?php echo $this->tag->form("login"); ?>
 
    <p>
        <label for="username">Username :</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>
 
    <p>
        <label for="password">Password  :</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
 
    <s>
        <?php echo $this->tag->submitButton("Log-in"); ?>
    </s>
    <br><br><br><br>
    <b>
    <a href="signup" class="btn "> Sign up </a><a href="index" class="btn "> Back </a>
</b>
</form>


</html>
