<!DOCTYPE html>
<html lang="en">
 
<head>
    <link rel="stylesheet" href="/database/public/css/TableEdit.css">
</head>
 
<body>
    <br><br><br><br><br>
    <div class="container">
        <div class="row">
               
            <div class="col-8 bg-light">
            <form action="/database/art/addsub/<?php echo $type?>/<?php echo $bo?>" method="post" enctype="multipart/form-data">
                <label for="name">Artname</label><br>
                <input type="text" name="name" id="name" placeholder="Enter.."><br>

                <label for="artist">Artist</label><br>
                <select name="artist" id="artist">
                <?php 
                $count = Artist::find();
                $num = count($count);
                for($i=1;$i<=$num;$i++)
                {
                    $art = Artist::findFirst([
                        'artist_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                    if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->artist_id;?>"><?php echo $art->artist_id." - ".$art->firstname." ".$art->midname." " .$art->lastname;?></option> 
                <?php
                }
                ?>                             
                </select>
                
                <label for="country">Country</label><br>
                <select name="country" id="country">
                <?php 
                $count = Country::find();
                $num = count($count);
                for($i=1;$i<=$num;$i++)
                {
                    $art = Country::findFirst([
                        'country_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                    if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->country_id;?>"><?php echo $art->country_id." - ".$art->country_title;?></option> 
                <?php
                }
                ?>                             
                </select>
                
                <label for="epoch">Epoch</label><br>
                <select name="epoch" id="epoch">
                <?php 
                $count2 = Epoch::find();
                $num = count($count2);
            
                for($i=1;$i<=$num;$i++)
                {
                    $art = Epoch::findFirst([
                        'epoch_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                    if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->epoch_id;?>"><?php echo $art->epoch_id." - ".$art->epoch_title;?></option>   
                <?php
                }
                ?>                             
                </select>


                
                <label for="des">Description</label><br>
                <textarea name="des" id="des" rows="10" cols="100" placeholder="Enter..."></textarea><br>

                <?php if($type == 1)
                {
                ?>
                <div>
                <br>
                <h3>Painting</h3>
                <label for="typeP">Paint_Type</label><br>
                <input type="text" name="typeP" id="typeP" placeholder="Enter.."><br>
                <label for="draw">Draw_On</label><br>
                <input type="text" name="draw" id="draw" placeholder="Enter.."><br>
                <label for="styleP">Style</label><br>
                <input type="text" name="styleP" id="styleP" placeholder="Enter.."><br>
                </div>

                <?php 
                }
                if($type == 2)
                {
                ?>

                <div>
                <br>
                <h3>Sculpture</h3>
                <label for="materialSc">Material</label><br>
                <input type="text" name="materialSc" id="materialSc" placeholder="Enter.."><br>
                <label for="heightSc">Height</label><br>
                <input type="text" name="heightSc" id="heightSc" placeholder="Enter.."><br>
                <label for="weightSc">Weight</label><br>
                <input type="text" name="weightSc" id="weightSc" placeholder="Enter.."><br>
                <label for="styleSc">Style</label><br>
                <input type="text" name="styleSc" id="styleSc" placeholder="Enter.."><br>
                </div>

                <?php 
                }
                if($type == 3)
                {
                ?>

                <div>
                <br>
                <h3>Statue</h3>
                <label for="materialSt">Material</label><br>
                <input type="text" name="materialSt" id="materialSt" placeholder="Enter.."><br>
                <label for="heightSt">Height</label><br>
                <input type="text" name="heightSt" id="heightSt" placeholder="Enter.."><br>
                <label for="weightSt">Weight</label><br>
                <input type="text" name="weightSt" id="weightSt" placeholder="Enter.."><br>
                <label for="styleSt">Style</label><br>
                <input type="text" name="styleSt" id="styleSt" placeholder="Enter.."><br>
                </div>

                <?php 
                }
                if($type == 4)
                {
                ?>

                <div>
                <br>
                <h3>Other</h3>
                <label for="typeO">Type</label><br>
                <input type="text" name="typeO" id="typeO" placeholder="Enter.."><br>
                <label for="styleSt">Style</label><br>
                <input type="text" name="styleO" id="styleO" placeholder="Enter.."><br>
                </div>

                <?php 
                }
                if($bo == 1)
                {
                ?>
                
                <div>
                <br>
                <h3>Borrow</h3>
                <label for="from">From</label><br>
                <input type="text" name="from" id="from" placeholder="Enter.."><br>
                <label for="acdate">Acquired_Date</label>
                <input type="date" name="acdate" id="acdate">
                <label for="redate">Return_Date</label>
                <input type="date" name="redate" id="redate"><br>
                <label for="coll">Collections</label><br>
                <select name="coll" id="coll">
                    <option value="0"> None </option> 
                <?php 
                $count = Collections::find();
                $num = count($count);
            
                for($i=1;$i<=$num;$i++)
                {
                    $art = Collections::findFirst([
                        'Collections_id = ?0',
                        'bind' => [
                            0 => $i,
                        ]
                    ]);
                if ($art === false) {$num++;continue;}
                ?>
                    <option value="<?php echo $art->Collections_id;?>"><?php echo $art->Collections_id." - ".$art->name;?></option> 
                <?php
                }
                ?>                             
                </select>
                </div>

                <?php 
                }
                if($bo == 2)
                {
                ?>

                <div>
                <br>
                <h3>Permanant</h3>
                <label for="status">Status</label><br>
                <input type="text" name="status" id="status" placeholder="Enter.."><br>
                <label for="cost">Cost</label><br>
                <input type="text" name="cost" id="cost" placeholder="Enter.."><br>
                <label for="date">Acquired_Date</label>
                <input type="date" name="date" id="date"><br>
                </div>

                <?php 
                }
                ?>

                <br>
                <h3>Select image to upload:</h3>
                <input type="file" name="fileToUpload" id="fileToUpload">   

                <input type="submit" value="Submit" name="submit">

            </form>
                <button class="button button1" onclick="window.location.href='/database/table'">Back</button>
            </div>
            

            </div>
        </div>
 
</body>
 
</html>