<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">

    </head>
 
    <body id="page-top" >

</body>
<br><br>
<h2>Welcome to Ours museum</h2>
<h1>Choose Type</h1>
<br>
<form action="pass" method="post">
  <input type="radio" name="type" value="1" checked> Painting<br>
  <input type="radio" name="type" value="2"> Sculpture<br>
  <input type="radio" name="type" value="3"> Statue<br>
  <input type="radio" name="type" value="4"> Other  

  <h1>Choose Borrow</h1>
  <br>
  <input type="radio" name="bo" value="1" checked> Borrow<br>
  <input type="radio" name="bo" value="2"> Permanant  

  <input type="submit" value="Submit">
</form> 


</html>
